/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.wrangler-types.env --include-runtime=false` (hash: b44a8259e90bccc10daa79f5487e5064)
interface __BaseEnv_Env {
	D1DB: D1Database;
	AI: Ai;
	PUBLIC_APP_URL: "https://zgidno-vidpovidno.web.app/";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_APP_URL">> {}
}
